### ISSUE TITLE
Request: Add some additional functions and features

### ISSUE THREAD

**Issue by iMrShadow** [BoyBaykiller/Ktx2.NET#1]
Hi! I am working on a texture converter, which extracts texture data from proprietary game files to DDS. However, some of the formats like ETC1, ETC2, ATC, ASTC, PVRTC etc. have to be stored in a KTX/KTX2 container and I would like to use this wrapper.

However, it doesn't support some functions equivalent to [DirectXTexNet's](https://github.com/deng0/DirectXTexNet/blob/master/DirectXTexNet/DirectXTexNet.cs#L911) ones which I use

It would be great to have some of these:
[WriteToMemory/WriteToFile](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/interface/python_binding/pyktx/ktx_texture.py#L222)
LoadFromFile
[ComputePitch/Slice](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/interface/python_binding/pyktx/ktx_texture.py#L143C4-L154C60)
[BitsPerPixel](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/external/dfdutils/vk2dfd.inl#L366) 
IsPremultipliedAlpha 

KTX1 writer and loader would be great as well, but I understand this is primarily for KTX2 and Khronos has decided to deprecate version 1 (which unfortunately supports ATC compressed textures natively).

Thanks.

**Comment by BoyBaykiller** [comment]
Hi, I l should be able to add these:
 * [BitsPerPixel](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/lib/texture2.c#L359)
 * [LoadFromFile](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/include/ktx.h#L1068) (add to internalexport.def)
 * [IsPremultipliedAlpha](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/include/ktx.h#L1112) (add to internalexport.def)
 * [WriteToFile](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/lib/writer2.c#L673) (add to internalexport.def)
 * [WriteToMemory](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/lib/writer2.c#L731) (add to internalexport.def)

But
 * [GetRowPitch](https://github.com/KhronosGroup/KTX-Software/blob/29aeddefd6d02630a3e8bcda7c6202aac4a58c77/lib/texture.c#L845) seems to be ktx1 only and like you said I'd rather not add ktx1 stuff.  From the KTX2 spec: Rows of uncompressed texture images must be tightly packed, equivalent to a GL_UNPACK_ALIGNMENT of 1

**Comment by iMrShadow** [comment]
Thanks a lot!

**Comment by BoyBaykiller** [comment]
I've added the following functions in version1.0.2:
* `Ktx2.CreateFromNamedFile`
* `Ktx2.WriteToNamedFile`
* `Ktx2.WriteToMemory`
* `Ktx2.GetPremultipliedAlpha`
* `Ktx2.Helper.GetDataFormatDescriptor`

Let me know if everything works! There are also some other changes to the interface.

**Comment by BoyBaykiller** [comment]
@iMrShadow

**Comment by iMrShadow** [comment]
Hello! Sorry for the late reply. 
Thanks for the update, I will try it in the upcoming week or 2, since I have limited time atm. I am closing this issue since the features were added. 

I will let you know if there are any issues
